### ISSUE TITLE
Setpoint vs readback fields always the same for motors

### ISSUE THREAD

**Issue by jsheppard95** [pcdshub/lucid#43] opened 2020-03-02 18:13 UTC
I have found that for `lucid`, the read back `.RBV` field for motors always agrees with it's set point `.VAL`. After an IOC reset, both are correct as the initial `.VAL` field is set to the current motor position and the `.RBV` agrees, but position fluctuations then throw the `.RBV` off, while `lucid` shows it continues to match `.VAL`, even after move requests. This is not the case for non-motor `pytmc` generated PVs, such as `gantry_y` or `gantry_x` for devices `mr1l0_lfe` and `mr2l0_lfe`.

Steps to reproduce:

`$ camonitor MR2L0:LFE:MMS:PITCH.RBV`
![lucid_val_rbv_issue](https://user-images.githubusercontent.com/37093966/75706763-9986d900-5c72-11ea-9893-54d9d82851ca.PNG)

**Comment by hhslepicka** [comment] 2020-03-02 19:48
So, the issue is that at the `pcdsdevices.mirror.XOffsetMirror` , pitch is defined as: `
pitch = Cpt(EpicsSignal, ':MMS:PITCH', kind='normal')`

With that, pitch is connecting to `<prefix>:MMS:PITCH` and not `<prefix>:MMS:PITCH.RBV`.

Closing as @jsheppard95 will address the fix at pcdsdevices.

**Closed by hhslepicka** 2020-03-02 19:48 UTC
