### ISSUE TITLE
Search doesn't work on LCLS linux hosts

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/lucid#38] opened 2020-02-26 22:25 UTC
As I try to type "im1" for example in the search bar, the focus gets lost and my typing is interrupted. When I click back to the box I get no search results. The highlighted circles appear when I've only got "i" typed in the search bar, but disappear at "im". When they've appeared, the circles are off-center.

This behavior was observed on psbuild-rhel7 and lfe-console

**Comment by hhslepicka** [comment] 2020-02-26 22:26
@ZLLentz over x and also locally?

**Comment by klauer** [comment] 2020-02-26 23:03
The circles do look a bit offset, admittedly. Running `lfe` and repeating what you did on psdev + psbuild, though, I can't reproduce the focus stealing and lack of search results. Hmm...

**Comment by ZLLentz** [comment] 2020-02-26 23:40
I only tried over x, since both of those machines can't really be accessed locally. I'll check if this happens on the control room machine or if it's just a "Zach's desktop" kind of problem.

**Comment by hhslepicka** [comment] 2020-02-27 00:25
What OS flavor is Zach's desktop? RHEL?

**Comment by ZLLentz** [comment] 2020-03-05 02:01
I never had time to really investigate this, but my desktop is:
```
$ uname -r
2.6.32-696.el6.x86_64
```
I `ssh -Y` to `psdev` and again to `lfe-console`
Then I source the setup scripts and open the `lfe` screen and encounter the issue. If it's `rhel6` through x-forwarding from Zach CPU only I can investigate later. I can show this to you tomorrow if you're curious as to what it looks like.

**Comment by klauer** [comment] 2020-03-05 17:19
We'd definitely like to see it, @ZLLentz, when @hhslepicka gets in.

**Comment by hhslepicka** [comment] 2020-03-06 00:29
I got in... I saw it... it is sad... 😞

**Comment by hhslepicka** [comment] 2020-03-06 23:59
This is due to the fact that linux is not respecting the `    self.setWindowFlag(Qt.WindowDoesNotAcceptFocus, True)` flag value and it results in a `focusOutEvent` at the Search line edit which causes the application to call `clear_highlight` closing the Search results dialog and removing the overlay from the grid.

I am working on a fix for that.

**Closed** 2020-03-07 00:16 UTC
