### ISSUE TITLE
Don't know if this is a pcdswidgets issue or a lucid issue, but HXR VAccum screen keeps closing when loading ion pump expert screens

### ISSUE THREAD

**Issue by slacAdpai** [pcdshub/lucid#44] opened 2020-03-02 20:18 UTC
```python
[adpai@lfe-console ~]$ source dev_conda
(dev) [adpai@lfe-console ~]$ lfe
(dev) [adpai@lfe-console ~]$ libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
QWidget::setLayout: Attempting to set QLayout "" on QFrame "interlock", which already has a layout
QWidget::setLayout: Attempting to set QLayout "" on QFrame "interlock", which already has a layout
/reg/g/pcds/pyps/apps/dev/pythonpath/pydm/widgets/shell_command.py:150: UserWarning: 'PyDMShellCommand.command' is deprecated, use 'PyDMShellCommand.commands' instead.
  warnings.warn("'PyDMShellCommand.command' is deprecated, "
CA.Client.Exception...............................................
    Warning: "Virtual circuit disconnect"
    Context: "ctl-lfe-rec03.pcdsn:5064"
    Source File: modules/ca/src/client/cac.cpp line 1237
    Current Time: Mon Mar 02 2020 11:24:31.238944147
..................................................................
[2020-03-02 11:33:52,031] [ERROR   ] - Unable to connect to 'TV2L0_PIP_01_pressure' during widget creation
[2020-03-02 11:33:52,034] [ERROR   ] - Unable to connect to 'TV2L0_PIP_01_high_voltage_do' during widget creation

(dev) [adpai@lfe-console ~]$ lfe
(dev) [adpai@lfe-console ~]$ libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
QWidget::setLayout: Attempting to set QLayout "" on QFrame "interlock", which already has a layout
QWidget::setLayout: Attempting to set QLayout "" on QFrame "interlock", which already has a layout
/reg/g/pcds/pyps/apps/dev/pythonpath/pydm/widgets/shell_command.py:150: UserWarning: 'PyDMShellCommand.command' is deprecated, use 'PyDMShellCommand.commands' instead.
  warnings.warn("'PyDMShellCommand.command' is deprecated, "
lfe
(dev) [adpai@lfe-console ~]$ libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
CA.Client.Exception...............................................
    Warning: "Virtual circuit disconnect"
    Context: "ctl-lfe-rec03.pcdsn:5064"
    Source File: modules/ca/src/client/cac.cpp line 1237
    Current Time: Mon Mar 02 2020 11:54:43.097265348
..................................................................
CA.Client.Exception...............................................
    Warning: "Virtual circuit disconnect"
    Context: "ctl-lfe-rec03.pcdsn:5064"
    Source File: modules/ca/src/client/cac.cpp line 1237
    Current Time: Mon Mar 02 2020 11:54:43.097284495
..................................................................

(dev) [adpai@lfe-console ~]$
(dev) [adpai@lfe-console ~]$
(dev) [adpai@lfe-console ~]$
(dev) [adpai@lfe-console ~]$
(dev) [adpai@lfe-console ~]$
(dev) [adpai@lfe-console ~]$ lfe
(dev) [adpai@lfe-console ~]$ libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
QWidget::setLayout: Attempting to set QLayout "" on QFrame "interlock", which already has a layout
QWidget::setLayout: Attempting to set QLayout "" on QFrame "interlock", which already has a layout
/reg/g/pcds/pyps/apps/dev/pythonpath/pydm/widgets/shell_command.py:150: UserWarning: 'PyDMShellCommand.command' is deprecated, use 'PyDMShellCommand.commands' instead.
  warnings.warn("'PyDMShellCommand.command' is deprecated, "
```

**Comment by hhslepicka** [comment] 2020-03-02 21:26
@slacAdpai I could not reproduce it here. Is there a specific Ion pump that is giving this error or any ion pump?

**Comment by hhslepicka** [comment] 2020-03-03 17:44
@slacAdpai since I can't reproduce it in here, do you mind to test it again and check if you still have the issue and report back?

**Comment by slacAdpai** [comment] 2020-03-04 23:39
Hello Hugo,

I pressed on probably 50 different vacuum ions and then it crashed again. No Lucid home screen no vacuum screens.

Here is the command line : 
```python 
[adpai@lfe-console ~]$ lfe
[adpai@lfe-console ~]$ libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
/reg/g/pcds/pyps/apps/dev/pythonpath/pydm/widgets/shell_command.py:150: UserWarning: 'PyDMShellCommand.command' is deprecated, use 'PyDMShellCommand.commands' instead.
  warnings.warn("'PyDMShellCommand.command' is deprecated, "
[2020-03-04 15:38:30,541] [ERROR   ] - No channel prefix specified.Cannot proceed with opening expert screen.
[2020-03-04 15:38:41,314] [ERROR   ] - Unable to connect to 'MR2L0_HOMS_GPI_01_pressure' during widget creation
```

**Comment by hhslepicka** [comment] 2020-03-05 00:12
Can you stop by and we can test it together?

**Comment by slacAdpai** [comment] 2020-03-05 20:54
Hello Hugo,

After about 100 clicks on widgets, the HXR vacuum screen is still crashing. The Lucid lfe console home screen did not crash.

Cheers,
Allen Pai

**Comment by hhslepicka** [comment] 2020-03-05 21:16
Can you identify a common pattern?

**Comment by hhslepicka** [comment] 2020-03-05 23:57
Next goal is to go 150... 🤣 ... it was 50 clicks, now 100..

**Comment by klauer** [comment] 2020-06-09 17:34
@slacAdpai are you still experiencing this?

**Comment by hhslepicka** [comment] 2020-06-23 23:02
Closing the issue after follow-up with @slacAdpai via SLACK DM.

**Closed by hhslepicka** 2020-06-23 23:02 UTC
